### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by ohjames**
`-T`

### CODE REVIEW

**Comment by ohjames** [comment]
As you know the automated tests are broken, but we tested this on our existing fairly complex flow project and the files are identical (to the character) afterwards. We then used the same schema on our typescript project where it generates valid typescript.

**Comment by brettjurgens** [comment]
@ohjames i think you're looking for [gql2ts](https://github.com/avantcredit/gql2ts), which this project is based on

**Comment by ohjames** [comment]
Oh and I see that project supports `flow` now also... probably should have used that in the first place lol.

**Comment by joarwilk** [comment]
@ohjames Yeah I will deprecate this in favour of that, no point having two identical repos.

**Comment by ohjames** [comment]
... and they have working tests also. Might wanna update the README to forward to that project.

**Pull request closed without merging**
