### PR TITLE
Use --export to export types rather than declare them, fixes #22

### LINKED ISSUE #22: Option to generate types using `export` rather than `declare`.
We want to be able to import types using `import`, not have every type globally declared.

### PR DESCRIPTION
**Pull request by ohjames**
Fixes #22

### CODE REVIEW

**Comment by ohjames** [comment]
Your tests are broken :(

**Comment by joarwilk** [comment]
Thanks for the PR! And yes, I dont have the time to fix them right now unfortunately 😕

**Comment by ohjames** [comment]
Thanks for accepting my PRs! I wish I could be more laid-back about tests and stuff... all cool... like the Fonz.

**Comment by pie6k** [comment]
Well. Thats great but it didnt add any notice to readme about that...

**Comment by ajarbol** [comment]
You should definitely update the documentation to expose this PR! Great job.

**Comment by ohjames** [comment]
@ajarbol @pie6k Seriously gql2ts is the project you want to use, not this one (yes it supports flow).

**Pull request merged**
